name: Sync repository

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone source repo
        run: |
          rm -rf source
          git clone --depth 1 https://github.com/TongSherbet/storage.git source

      - name: Sync source into storage folder
        run: |
          rm -rf storage
          mkdir storage
          cp -r source/. storage/
          rm -rf source

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add storage

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Sync storage repository"
            git push
          fi
